
## 测试环境
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.16.16.31:3306/t_toread?useUnicode=true&amp;characterEncoding=UTF-8
  username: dev_sms
  password: ziroomdb


logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

spring:
  profiles:
    active: test
  application:
    name: ferrari