jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.16.16.13:3306:3306/ferrari?useUnicode=true&amp;characterEncoding=UTF-8
  username: dev_bsrd
  password: ziroomdb


logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

spring:
  profiles:
    active: pro
  application:
    name: ferrari


server:
  port: 8081



